{
  'includes': [
    # Bring in the autogenerated source file lists.
    'deps/cef/cef_paths.gypi',
   ],
  'variables': {
    'includes_common': [
      'deps/cef/include/cef_base.h',
      'deps/cef/include/cef_pack_resources.h',
      'deps/cef/include/cef_pack_strings.h',
      'deps/cef/include/cef_runnable.h',
      'deps/cef/include/cef_version.h',
      'deps/cef/include/internal/cef_build.h',
      'deps/cef/include/internal/cef_export.h',
      'deps/cef/include/internal/cef_ptr.h',
      'deps/cef/include/internal/cef_string.h',
      'deps/cef/include/internal/cef_string_list.h',
      'deps/cef/include/internal/cef_string_map.h',
      'deps/cef/include/internal/cef_string_multimap.h',
      'deps/cef/include/internal/cef_string_types.h',
      'deps/cef/include/internal/cef_string_wrappers.h',
      'deps/cef/include/internal/cef_time.h',
      'deps/cef/include/internal/cef_tuple.h',
      'deps/cef/include/internal/cef_types.h',
      'deps/cef/include/internal/cef_types_wrappers.h',
      '<@(autogen_cpp_includes)',
    ],
    'includes_capi': [
      'deps/cef/include/capi/cef_base_capi.h',
      '<@(autogen_capi_includes)',
    ],
    'includes_wrapper': [
      'deps/cef/include/wrapper/cef_byte_read_handler.h',
      'deps/cef/include/wrapper/cef_stream_resource_handler.h',
      'deps/cef/include/wrapper/cef_xml_object.h',
      'deps/cef/include/wrapper/cef_zip_archive.h',
    ],
    'includes_win': [
      'deps/cef/include/internal/cef_types_win.h',
      'deps/cef/include/internal/cef_win.h',
    ],
    'includes_mac': [
      'deps/cef/include/cef_application_mac.h',
      'deps/cef/include/internal/cef_mac.h',
      'deps/cef/include/internal/cef_types_mac.h',
    ],
    'includes_linux': [
      'deps/cef/include/internal/cef_linux.h',
      'deps/cef/include/internal/cef_types_linux.h',
    ],
    'libcef_sources_common': [
      'deps/cef/libcef_dll/cef_logging.h',
      'deps/cef/libcef_dll/cpptoc/cpptoc.h',
      'deps/cef/libcef_dll/ctocpp/ctocpp.h',
      'deps/cef/libcef_dll/libcef_dll.cc',
      'deps/cef/libcef_dll/libcef_dll2.cc',
      'deps/cef/libcef_dll/resource.h',
      'deps/cef/libcef_dll/transfer_util.cpp',
      'deps/cef/libcef_dll/transfer_util.h',
      '<@(autogen_library_side)',
    ],
    'libcef_dll_wrapper_sources_common': [
      'deps/cef/libcef_dll/cef_logging.h',
      'deps/cef/libcef_dll/cpptoc/base_cpptoc.h',
      'deps/cef/libcef_dll/cpptoc/cpptoc.h',
      'deps/cef/libcef_dll/ctocpp/base_ctocpp.h',
      'deps/cef/libcef_dll/ctocpp/ctocpp.h',
      'deps/cef/libcef_dll/transfer_util.cpp',
      'deps/cef/libcef_dll/transfer_util.h',
      'deps/cef/libcef_dll/wrapper/cef_byte_read_handler.cc',
      'deps/cef/libcef_dll/wrapper/cef_stream_resource_handler.cc',
      'deps/cef/libcef_dll/wrapper/cef_xml_object.cc',
      'deps/cef/libcef_dll/wrapper/cef_zip_archive.cc',
      'deps/cef/libcef_dll/wrapper/libcef_dll_wrapper.cc',
      'deps/cef/libcef_dll/wrapper/libcef_dll_wrapper2.cc',
      '<@(autogen_client_side)',
    ],
    'breach_sources_common': [
      'breach/handler.cpp',
      'breach/handler.h',
    ],
    'breach_sources_win': [
    ],
    'breach_sources_mac': [
    ],
    'breach_sources_mac_helper': [
    ],
    'breach_bundle_resources_mac': [
    ],
    'breach_sources_linux': [
    ],
    'breach_bundle_resources_linux': [
    ],
  },
}
